#!/bin/sh
#WINIT_HIDPI_FACTOR=1
#WINIT_X11_SCALE_FACTOR=1
# xwallpaper --zoom ~/.config/wall.jpg &
remaps &	# Remap caps key esc & speedy keys
sxhkd -m -1 & 	#(To escape xbind keys)
setbg & 	#(Pywal and wall)
picom -b &
pamixer --set-volume 75 &
xbacklight -set 12 &
dwmblocks &
#flashfocus &
pipewire &
pipewire-pulse &
pipewire-media-session &
sudo wifi off &
sudo bluetooth off &
# sudo mkdir /run/user/1000 &
sudo chown shahid -R /run/user/* &
sudo hwclock --hctosys &
# emacs --daemon &
