---
title: Sufism a Gentle Introduction
author: Mohammed Shahid^[B.Tech Information Technology, shahid.xyz@yahoo.com]
output: pdf_document
fontsize: 10pt
---

# Sufism

All true Sufi tariqas have a lineage that is
traceable to Prophet Muhammad (peace be upon him)
through his son-in-law Hazreti Ali (may Allah be
pleased with him) or Hz. Abu Bakr (may Allah be
pleased with him).

The idea is that how to do zikr and becoming wali
of allah according to hadith and some secret
prayer or zikr methos that only knows to prophet
and his family and his best friend and father in
law Abu Bakr.

These methods were passed down through generations
and are the foundation upon which the Sufi tariqas
were later established.

The various Sufi tariqas (Sufi orders; literally,
paths) were established by their founders in
response to the needs of different kinds of
people. If a person is drawn to a particular
school of Sufism, such as the Qadiri Tariqa or
Mevlevi Tariqa, it is because that school has a
flavor or character that addresses the particular
needs of that individual. This can be thought
of in the same light as vocational schools. If
a person has a deep desire to become a chef of
Chinese cuisine, he does not go to a master of
French cuisine for training. Likewise, each
spiritual seeker has a particular character that
can be well served by a tariqa suited to his or
her personality.


While everyone is welcomed as a guest, it is
understood that a true shaykh will recognize the
people who belong to him or her and can only
accept his or her own spiritual “children" as
murids (students of Sufism; lit., committed ones).


Among the true tariqas there is general agreement
about the essential tenets of Sufism. There is no
competition among the tariqas. No tariqa claims
that they have the one true way, or that it is
higher than other orders.

